name: Example

on:
  push:
    branches:
      - some_branch
jobs:
  alpine-nopin:
    runs-on: ubuntu-latest
    container: alpine  # Noncompliant

    steps:
      - run: |
          cat /etc/os-release
