name: Example

on:
  pull_request:
    branches: [ some_branch ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Example Step
        run: |
          echo "PR title: ${{ github.event.pull_request.title }}"